# modified from: https://linuxhint.com/lamp_server_docker/
# Use root/example as user/password credentials
version: '3.1'

services:
  mydb:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
    volumes:
      #- /usr/local/mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql
      # load SQL from ./mysql directory
      - ./mysql/:/docker-entrypoint-initdb.d
    ports:
      - 3000:3306

volumes:
  mysql-data:
